### ISSUE TITLE
Missing content types

### ISSUE THREAD

**Issue by vmiimu** [morethanthemes/startupgrowth-lite#1]
After successfully setting up the demo site from this repo, I was unable to locate the [various content types and views referenced on the StartupGrowth:Documentation page](http://wiki.morethanthemes.com/index.php?title=StartupGrowth:Documentation).

Do these need to be installed / created separately?
Are there any additional instructions I've missed in order to replicate the demo site locally as stated on the project page?

> You are welcome however to grab this code and have the demonstration site running on your end. By doing this you have the chance to see the "Startup Growth Lite" theme in action exactly the way it looks like on our demo.

A duplicate issue for this problem is also posted on the Startup Growth Lite Drupal project issue page:
https://www.drupal.org/node/2516638

**Comment by vkechagias** [comment]
The content types mentioned in the wiki link are part of the premium Drupal theme that Startup Growth Lite is based on.

If you want a more detail presentation of the Startup Growth premium theme please check the following URL:
https://morethanthemes.com/themes/startupgrowth
